# Generated by Django 5.0.7 on 2024-08-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_users_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
