# Generated by Django 5.0.7 on 2024-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='PURname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
