# Generated by Django 5.0.7 on 2024-08-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_user_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
