# Generated by Django 5.0.7 on 2024-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserImages', '0003_upimage_a_imageslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='upimage',
            name='Plikes',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
