# Generated by Django 5.0.7 on 2024-08-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserImages', '0004_upimage_plikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upimage',
            name='Plikes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
