# Generated by Django 5.0.7 on 2024-08-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserImages', '0005_alter_upimage_plikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upimage',
            name='Pdislikes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
