# Generated by Django 5.0.7 on 2024-08-10 15:11

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Utitel', models.CharField(max_length=50)),
                ('Upost_blog', models.TextField(max_length=5000)),
                ('Upost_image', models.ImageField(default=None, null=True, upload_to='blog/')),
                ('Udate_of_post', models.DateField()),
                ('Upost_category', models.CharField(max_length=30)),
                ('Uproimage', models.ImageField(default=None, null=True, upload_to='user/')),
                ('Uname', models.CharField(max_length=100)),
                ('UFname', models.CharField(max_length=100)),
                ('A_slugUserBlog', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Utitel', unique=True)),
            ],
        ),
    ]
