# Generated by Django 5.0.7 on 2024-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ublog',
            name='UFname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
