# Generated by Django 5.0.7 on 2024-08-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBlogs', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
