# Generated by Django 5.0.7 on 2024-08-08 09:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_post_image_alter_blogs_post_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='A_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
